#oc apply -f atmoz-sftp.yaml 


#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: sftp-data-pv
#  labels:
#    app: sftp
#spec:
#  storageClassName: "aws-ebs"
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftp-data-pvc
  namespace: openrota--sftp
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: "aws-ebs"

---

kind: Service
apiVersion: v1
metadata:
  name: sftp-service
  namespace: openrota--sftp
  labels:
    environment: production
spec:
  type: "LoadBalancer"
  ports:
  - name: "ssh"
    # don't use the default part, to allow the machine this runs on to be accessed using ssh
    port: 23
    targetPort: 22
  selector:
    app: sftp
status:
  loadBalancer: {}

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: sftp-deployment
  namespace: openrota--sftp
  labels:
    environment: production
    app: sftp
spec:
  # how many pods and indicate which strategy we want for rolling update
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      environment: production
      app: sftp

  template:
    metadata:
      labels:
        environment: production
        app: sftp

    spec:
      # secrets and config
      volumes:
        - name: sftp-client-public-keys
          secret:
            secretName: sftp-client-public-keys
        - name: sftp-host-keys
          secret:
            secretName: sftp-host-keys
            defaultMode: 0600
        - name: sftp-data
          persistentVolumeClaim:
            claimName: sftp-data-pvc
      serviceAccountName: sftp-anyuid-service-account
      containers:
        # the sftp server itself
        - name: sftp
          # use kalioz/sftp:latest instead of atmoz/sftp:latest if you need arm compatibility
          image: atmoz/sftp:latest
          imagePullPolicy: IfNotPresent
          # create users and dirs
          # user:password:uid:gid:directories
          args: ["user:password:::incoming,outgoing"]
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /home/myUser/.ssh/keys
              name: sftp-client-public-keys
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key
              name: sftp-host-keys
              subPath: ssh_host_rsa_key
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_rsa_key.pub
              name: sftp-host-keys
              subPath: ssh_host_rsa_key.pub
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key
              name: sftp-host-keys
              subPath: ssh_host_ed25519_key
              readOnly: true
            - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              name: sftp-host-keys
              subPath: ssh_host_ed25519_key.pub
              readOnly: true
            - mountPath: /home/myUser
              name: sftp-data
          securityContext:
            privileged: true


---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: atmoz-sftp-route
  namespace: openrota--sftp
spec:
  to:
    kind: Service
    name: sftp-service
